markdown: kramdown
kramdown:
  math_engine: mathjax
  mathjax_config:
    tex2jax:
      {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        displayMath: [['$$', '$$'], ['\\[', '\\]']],
      }
